"""edit numeric in product model

Revision ID: 94a6d571cf54
Revises: 7940b4c3d74b
Create Date: 2025-11-04 16:17:50.092512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a6d571cf54'
down_revision: Union[str, Sequence[str], None] = '7940b4c3d74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.NUMERIC(precision=1, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'rating',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=1, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
